on:
  push:
    branches:
      - main  # Triggered when there is a new push to the `main` branch

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure VM
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python dependencies for code checks
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      # Lint and format check
      - name: Lint and Format Check
        run: |
          isort --check-only .  # 导入顺序检查
          black --check .  # 格式化检查
          flake8 .  # 代码质量检查

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build --no-cache -t ghcr.io/wordiverse/fitness-app-docker:${{ github.sha }} .

      # Push Docker image to GitHub Container Registry
      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/wordiverse/fitness-app-docker:${{ github.sha }}

      # Set SSH key
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}" > course-vm_key.pem
          chmod 600 course-vm_key.pem

      # Login and deploy to Azure VM
      - name: Login and Deploy to Azure VM
        run: |
          ssh -i course-vm_key.pem -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/wordiverse/fitness-app-docker:${{ github.sha }}

            docker stop fitness-container || true
            docker rm fitness-container || true

            docker images --filter "dangling=true" -q | xargs -r docker rmi
            docker images ghcr.io/wordiverse/fitness-app-docker --filter "before=ghcr.io/wordiverse/fitness-app-docker:${{ github.sha }}" -q | xargs -r docker rmi

            docker run -d --name fitness-container \
              -e GITHUB_SHA="${{ github.sha }}" \
              -e ALGORITHM="${{ secrets.ALGORITHM }}" \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
              -e PINECONE_API_KEY="${{ secrets.PINECONE_API_KEY }}" \
              -e GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" \
              -e DEBUG="${{ secrets.DEBUG }}" \
              -p 80:8000 ghcr.io/wordiverse/fitness-app-docker:${{ github.sha }}
          EOF

      # Clean SSH keys
      - name: Cleanup SSH Key
        run: rm -f course-vm_key.pem
