on:
  push:
    branches:
      - main  # 在 `main` 分支有新的推送时触发

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure VM
    runs-on: ubuntu-latest

    steps:
      # Checkout 源代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录到 GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/wordiverse/fitness-app-docker:latest .

      # 推送 Docker 镜像到 GitHub Container Registry
      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/wordiverse/fitness-app-docker:latest

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}" > course-vm_key.pem
          chmod 600 course-vm_key.pem

      - name: Login and Deploy to Azure VM
        run: |
          ssh -i course-vm_key.pem -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/wordiverse/fitness-app-docker:latest
            docker stop fitness-container || true
            docker rm fitness-container || true
            docker run -d --name fitness-container -p 80:8000 ghcr.io/wordiverse/fitness-app-docker:latest
          EOF

      # 清理 SSH 密钥
      - name: Cleanup SSH Key
        run: rm -f course-vm_key.pem